// <auto-generated />
using System;
using E_Learning_Platform.Infrastracture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Learning_Platform.Infrastracture.Data.Migrations.Version1
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcademicYears", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SessionsPerMonth")
                        .HasColumnType("int");

                    b.Property<int>("SessionsPerWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("ClassGroups", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId", "Name")
                        .IsUnique();

                    b.ToTable("Semesters", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId");

                    b.ToTable("Sessions", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.StudentClassGroup", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentEnrollmentProcessStudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentEnrollmentProcessTeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "ClassGroupId");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentEnrollmentProcessStudentId", "StudentEnrollmentProcessTeacherSubjectId");

                    b.ToTable("StudentClassGroups", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Subjects", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tracks", "Academic");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("Conversations", "Communication");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("ConverstionParticipants", "Communication");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", "Communication");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AvailableUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EstimatedDurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("ContentItems", "Courseware");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ImportedQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateOptionsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ImportedQuestionBatchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bit")
                        .HasComputedColumnSql("CASE WHEN Status = 'Approved' THEN 1 ELSE 0 END");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuggestedDifficulty")
                        .HasColumnType("int");

                    b.Property<int?>("SuggestedQuestionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImportedQuestionBatchId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("ImportedQuestions", "Courseware");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ImportedQuestionBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("ProcessedByAI")
                        .HasColumnType("bit");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TotalExtractedQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ImportedByUserId");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("ImportedQuestionBatches", "Courseware");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("Lessons", "Courseware");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImportedByAI")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionHeader")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightAnswer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LessonId");

                    b.ToTable("Questions", "Courseware");

                    b.HasDiscriminator<string>("QuestionType").HasValue("Essay");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MCQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MCQuestionId");

                    b.ToTable("QuestionOptions", "Courseware");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.QuestionReview", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuestionApprovalStatus")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "ReviewedById", "ReviewedAt");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("QuestionReviews", "Courseware");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.ExamQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OfficialExamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DifficultyOverride")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("QuestionId", "OfficialExamId");

                    b.HasIndex("OfficialExamId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamQuestions", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.ExamStudentAnswer", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OfficialExamId")
                        .HasColumnType("int");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "QuestionId", "OfficialExamId");

                    b.HasIndex("OfficialExamId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamStudentAnswers", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("OfficialExams", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExamLesson", b =>
                {
                    b.Property<int>("OfficialExamId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OfficialExamId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("OfficialExamLessons");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExamStudent", b =>
                {
                    b.Property<int>("OfficialExamId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("OfficialExamId", "StudentId");

                    b.HasIndex("OfficialExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("OfficialExamStudents", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("PracticeSessions", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSessionLesson", b =>
                {
                    b.Property<int>("PracticeSessionId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionsAttempted")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("PracticeSessionId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("PracticeSessionLessons", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSessionStudentAnswer", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("PracticeSessionId")
                        .HasColumnType("int");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "QuestionId", "PracticeSessionId");

                    b.HasIndex("PracticeSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("PracticeSessionStudentAnswers", "Examination");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.InvitationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("InvitationCodes", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentAttendance", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("AttendanceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "SessionId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("StudentAttendances", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentEnrollmentProcess", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvitationCodeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "TeacherSubjectId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("InvitationCodeId");

                    b.HasIndex("Status");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("StudentEnrollmentProcesses", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentInvitationCode", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("InvitationCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "InvitationCodeId");

                    b.HasIndex("InvitationCodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentInvitationCodes", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentParentApproval", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "ParentId", "TeacherSubjectId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("ParentId");

                    b.HasIndex("TeacherSubjectId");

                    b.ToTable("StudentParentApprovals", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContentItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FirstOpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Interactions")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherFeedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("StudentId", "ContentItemId");

                    b.ToTable("StudentProgresses", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PayerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherSubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PayerUserId");

                    b.HasIndex("StudentId", "TeacherSubjectId");

                    b.ToTable("Transactions", "Operations");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("NationalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("NationalId");

                    b.ToTable("ApplicationUsers", "Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.StudentParent", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "ParentId");

                    b.HasIndex("ParentId");

                    b.ToTable("StudentParents", "Users");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.TeacherAssistant", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("AssistantId")
                        .HasColumnType("int");

                    b.Property<bool>("CanApproveParents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanApproveStudents")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageQuestions")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TeacherId", "AssistantId");

                    b.HasIndex("AssistantId");

                    b.ToTable("TeacherAssistants", "Users");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.MCQuestion", b =>
                {
                    b.HasBaseType("E_Learning_Platform.Core.Entities.Courseware.Question");

                    b.ToTable("Questions", "Courseware");

                    b.HasDiscriminator().HasValue("MCQ");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Parent", b =>
                {
                    b.HasBaseType("E_Learning_Platform.Core.Entities.Users.ApplicationUser");

                    b.ToTable("Parents", "Users");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Student", b =>
                {
                    b.HasBaseType("E_Learning_Platform.Core.Entities.Users.ApplicationUser");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.ToTable("Students", "Users");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Teacher", b =>
                {
                    b.HasBaseType("E_Learning_Platform.Core.Entities.Users.ApplicationUser");

                    b.Property<DateTimeOffset>("JoinDate")
                        .HasColumnType("datetimeoffset");

                    b.ToTable("Teachers", "Users");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.TeachingAssistant", b =>
                {
                    b.HasBaseType("E_Learning_Platform.Core.Entities.Users.ApplicationUser");

                    b.ToTable("TeachingAssistants", "Users");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.TOFQuestion", b =>
                {
                    b.HasBaseType("E_Learning_Platform.Core.Entities.Courseware.MCQuestion");

                    b.ToTable("Questions", "Courseware");

                    b.HasDiscriminator().HasValue("TOF");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.ClassGroup", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("ClassGroups")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Semester", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.AcademicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Session", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.ClassGroup", "ClassGroup")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.StudentClassGroup", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.ClassGroup", "ClassGroup")
                        .WithMany("StudentClassGroups")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("StudentClassGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Operations.StudentEnrollmentProcess", "StudentEnrollmentProcess")
                        .WithMany("StudentClassGroups")
                        .HasForeignKey("StudentEnrollmentProcessStudentId", "StudentEnrollmentProcessTeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassGroup");

                    b.Navigation("Student");

                    b.Navigation("StudentEnrollmentProcess");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Subject", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.Track", "Track")
                        .WithMany("Subjects")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.Semester", "Semester")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.Conversation", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.ClassGroup", "ClassGroup")
                        .WithMany()
                        .HasForeignKey("ClassGroupId");

                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany()
                        .HasForeignKey("TeacherSubjectId");

                    b.Navigation("ClassGroup");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.ConversationParticipant", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Communication.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.Message", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Communication.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ContentItem", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Lesson", "Lesson")
                        .WithMany("ContentItems")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ImportedQuestion", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.ImportedQuestionBatch", "Batch")
                        .WithMany("ImportedQuestions")
                        .HasForeignKey("ImportedQuestionBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.Navigation("Batch");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ImportedQuestionBatch", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "ImportedByUser")
                        .WithMany()
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("ImportedQuestionBatches")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportedByUser");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.Lesson", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.Question", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.QuestionOption", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.MCQuestion", "MCQuestion")
                        .WithMany("Options")
                        .HasForeignKey("MCQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MCQuestion");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.QuestionReview", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", null)
                        .WithMany("ReviewsMade")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Question", "Question")
                        .WithMany("Reviews")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.ExamQuestion", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Examination.OfficialExam", "OfficialExam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("OfficialExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficialExam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.ExamStudentAnswer", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Examination.OfficialExam", "OfficialExam")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("OfficialExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Question", "Question")
                        .WithMany("ExamStudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("StudentExamAnswers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficialExam");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExam", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("OfficialExams")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExamLesson", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Lesson", "Lesson")
                        .WithMany("OfficialExamLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Examination.OfficialExam", "OfficialExam")
                        .WithMany("OfficialExamLessons")
                        .HasForeignKey("OfficialExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("OfficialExam");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExamStudent", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Examination.OfficialExam", "OfficialExam")
                        .WithMany("OfficialExamStudents")
                        .HasForeignKey("OfficialExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficialExam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSession", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("PracticeSessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSessionLesson", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Lesson", "Lesson")
                        .WithMany("PracticeSessionLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Examination.PracticeSession", "PracticeSession")
                        .WithMany("PracticeSessionLessons")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("PracticeSession");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSessionStudentAnswer", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Examination.PracticeSession", "PracticeSession")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.Question", "Question")
                        .WithMany("PracticeSessionStudentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("StudentPracticeSessionAnswers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PracticeSession");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.InvitationCode", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("InvitationCodes")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentAttendance", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.Session", "Session")
                        .WithMany("StudentAttendances")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedByUser");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentEnrollmentProcess", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("E_Learning_Platform.Core.Entities.Operations.InvitationCode", "InvitationCode")
                        .WithMany()
                        .HasForeignKey("InvitationCodeId");

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("Enrollments")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("InvitationCode");

                    b.Navigation("Student");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentInvitationCode", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Operations.InvitationCode", "InvitationCode")
                        .WithMany()
                        .HasForeignKey("InvitationCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("InvitationCodes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitationCode");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentParentApproval", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Parent", "Parent")
                        .WithMany("ChildApprovals")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("ParentApprovals")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", "TeacherSubject")
                        .WithMany("ParentApprovals")
                        .HasForeignKey("TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("TeacherSubject");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentProgress", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Courseware.ContentItem", "ContentItem")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.Transaction", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", "Payer")
                        .WithMany()
                        .HasForeignKey("PayerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Operations.StudentEnrollmentProcess", "StudentEnrollment")
                        .WithMany("Transactions")
                        .HasForeignKey("StudentId", "TeacherSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payer");

                    b.Navigation("StudentEnrollment");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.StudentParent", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Student", "Student")
                        .WithMany("Parents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.TeacherAssistant", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.TeachingAssistant", "Assistant")
                        .WithMany("AssignedTeachers")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Learning_Platform.Core.Entities.Users.Teacher", "Teacher")
                        .WithMany("Assistants")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assistant");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Parent", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("E_Learning_Platform.Core.Entities.Users.Parent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Student", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("E_Learning_Platform.Core.Entities.Users.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Teacher", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("E_Learning_Platform.Core.Entities.Users.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.TeachingAssistant", b =>
                {
                    b.HasOne("E_Learning_Platform.Core.Entities.Users.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("E_Learning_Platform.Core.Entities.Users.TeachingAssistant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.AcademicYear", b =>
                {
                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.ClassGroup", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("StudentClassGroups");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Semester", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Session", b =>
                {
                    b.Navigation("StudentAttendances");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.TeacherSubject", b =>
                {
                    b.Navigation("ClassGroups");

                    b.Navigation("Enrollments");

                    b.Navigation("ImportedQuestionBatches");

                    b.Navigation("InvitationCodes");

                    b.Navigation("Lessons");

                    b.Navigation("OfficialExams");

                    b.Navigation("ParentApprovals");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Academic.Track", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Communication.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ContentItem", b =>
                {
                    b.Navigation("StudentProgresses");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.ImportedQuestionBatch", b =>
                {
                    b.Navigation("ImportedQuestions");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.Lesson", b =>
                {
                    b.Navigation("ContentItems");

                    b.Navigation("OfficialExamLessons");

                    b.Navigation("PracticeSessionLessons");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.Question", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("ExamStudentAnswers");

                    b.Navigation("PracticeSessionStudentAnswers");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.OfficialExam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("OfficialExamLessons");

                    b.Navigation("OfficialExamStudents");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Examination.PracticeSession", b =>
                {
                    b.Navigation("PracticeSessionLessons");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Operations.StudentEnrollmentProcess", b =>
                {
                    b.Navigation("StudentClassGroups");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("ReviewsMade");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Courseware.MCQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Parent", b =>
                {
                    b.Navigation("ChildApprovals");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("InvitationCodes");

                    b.Navigation("ParentApprovals");

                    b.Navigation("Parents");

                    b.Navigation("PracticeSessions");

                    b.Navigation("ProgressRecords");

                    b.Navigation("StudentClassGroups");

                    b.Navigation("StudentExamAnswers");

                    b.Navigation("StudentPracticeSessionAnswers");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.Teacher", b =>
                {
                    b.Navigation("Assistants");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("E_Learning_Platform.Core.Entities.Users.TeachingAssistant", b =>
                {
                    b.Navigation("AssignedTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
